"""ZAHRA fine-tune script (LoRA on CPU/GPU, no LLaMA).

Fine-tunes an open-source base model (default: Qwen2.5-Coder 1.5B, Apache-2.0)
with the dataset generated by ``ai_agent.zahra_dataset`` so the model's
weights absorb ZAHRA's features: attack knowledge, learned skills, past
experiences and local documents.

Setup (one time):
    pip install torch transformers accelerate peft datasets

Usage:
    python -m ai_agent.zahra_finetune                     # CPU, 1.5B, 1 epoch
    python -m ai_agent.zahra_finetune --gpu               # CUDA if available
    python -m ai_agent.zahra_finetune --epochs 3 --lr 2e-4
    python -m ai_agent.zahra_finetune --model google/gemma-2b-it   # any open model

After training, the adapter is saved to zahra_model/zahra-adapter and
merged weights to zahra_model/zahra-finetuned (GGUF conversion optional).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

DATASET = ROOT / "zahra_model" / "training" / "zahra_train.jsonl"
ADAPTER_DIR = ROOT / "zahra_model" / "zahra-adapter"
MERGED_DIR = ROOT / "zahra_model" / "zahra-finetuned"


def main() -> int:
    parser = argparse.ArgumentParser(description="Fine-tune ZAHRA (LoRA)")
    parser.add_argument("--data", default=str(DATASET))
    parser.add_argument("--model", default="Qwen/Qwen2.5-Coder-1.5B-Instruct")
    parser.add_argument("--out", default=str(ADAPTER_DIR))
    parser.add_argument("--epochs", type=int, default=1)
    parser.add_argument("--lr", type=float, default=2e-4)
    parser.add_argument("--gpu", action="store_true", help="Use CUDA if available")
    parser.add_argument("--max-len", type=int, default=1024)
    parser.add_argument("--batch", type=int, default=1)
    parser.add_argument("--limit", type=int, default=0,
                        help="Train on only the first N samples (smoke test)")
    parser.add_argument("--max-steps", type=int, default=-1,
                        help="Cap total optimizer steps (smoke test)")
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    try:
        import torch
        from transformers import (
            AutoModelForCausalLM,
            AutoTokenizer,
            Trainer,
            TrainingArguments,
        )
        from datasets import Dataset
        from peft import LoraConfig, get_peft_model
    except ImportError as exc:
        print(f"[ZAHRA-TRAIN] missing dependency: {exc}")
        print("Run: pip install torch transformers accelerate peft datasets")
        return 1

    device = "cuda" if (args.gpu and torch.cuda.is_available()) else "cpu"
    if args.gpu and not torch.cuda.is_available():
        print("[ZAHRA-TRAIN] --gpu requested but no CUDA found; falling back to CPU.")

    print(f"[ZAHRA-TRAIN] base model: {args.model}")
    print(f"[ZAHRA-TRAIN] device: {device}")
    print(f"[ZAHRA-TRAIN] loading dataset: {args.data}")
    if not Path(args.data).exists():
        print("Run `python -m ai_agent.zahra_dataset` first.")
        return 1

    tokenizer = AutoTokenizer.from_pretrained(
        args.model, trust_remote_code=True, use_fast=False)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    def fmt(example):
        # Train ONLY on the assistant answer. Prompt tokens get label -100
        # so the model learns to respond well, not to parrot the prompt.
        prompt = tokenizer.apply_chat_template(
            [
                {"role": "system", "content": example["system"]},
                {"role": "user", "content": example["user"]},
            ],
            tokenize=False, add_generation_prompt=True,
        )
        answer = example["answer"]
        p_enc = tokenizer(prompt, truncation=True, max_length=args.max_len // 2)
        a_enc = tokenizer(answer, truncation=True, max_length=args.max_len - len(p_enc["input_ids"]))
        input_ids = p_enc["input_ids"] + a_enc["input_ids"] + [tokenizer.eos_token_id]
        input_ids = input_ids[: args.max_len]
        labels = [-100] * len(p_enc["input_ids"]) + \
            input_ids[len(p_enc["input_ids"]):]
        return {"input_ids": input_ids, "attention_mask": [1] * len(input_ids),
                "labels": labels}

    import json
    raw = [json.loads(l) for l in open(args.data, encoding="utf-8") if l.strip()]
    if args.limit > 0:
        raw = raw[: args.limit]
        print(f"[ZAHRA-TRAIN] smoke test: using first {args.limit} samples.")
    ds = Dataset.from_list(raw).map(fmt, remove_columns=["system", "user", "answer"])
    print(f"[ZAHRA-TRAIN] {len(ds)} samples ready.")

    model = AutoModelForCausalLM.from_pretrained(
        args.model, trust_remote_code=True,
        torch_dtype=torch.float32 if device == "cpu" else torch.float16,
        low_cpu_mem_usage=True,
    ).to(device)

    lora = LoraConfig(
        r=16, lora_alpha=32, target_modules=["q_proj", "k_proj", "v_proj", "o_proj",
                                             "gate_proj", "up_proj", "down_proj"],
        lora_dropout=0.05, bias="none", task_type="CAUSAL_LM",
    )
    model = get_peft_model(model, lora)
    model.print_trainable_parameters()

    out_dir = Path(args.out)
    merged_dir = out_dir.parent / "zahra-finetuned"

    train_args = TrainingArguments(
        output_dir=str(out_dir),
        per_device_train_batch_size=args.batch,
        gradient_accumulation_steps=8,
        num_train_epochs=args.epochs,
        learning_rate=args.lr,
        lr_scheduler_type="cosine",
        warmup_ratio=0.05,
        logging_steps=10,
        save_strategy="epoch",
        save_total_limit=2,
        report_to=[],
        seed=args.seed,
        fp16=False if device == "cpu" else True,
        max_steps=args.max_steps if args.max_steps > 0 else -1,
    )
    trainer = Trainer(model=model, args=train_args,
                      train_dataset=ds)
    print("[ZAHRA-TRAIN] training...")
    trainer.train()
    model.save_pretrained(str(out_dir))
    tokenizer.save_pretrained(str(out_dir))
    print(f"[ZAHRA-TRAIN] adapter saved to {out_dir}")

    print("[ZAHRA-TRAIN] merging adapter into full weights...")
    merged = model.merge_and_unload()
    merged_dir.mkdir(parents=True, exist_ok=True)
    merged.save_pretrained(str(merged_dir))
    tokenizer.save_pretrained(str(merged_dir))
    print(f"[ZAHRA-TRAIN] merged model saved to {merged_dir}")

    print("\nNext steps:")
    print("  1) Convert to GGUF:  git clone https://github.com/ggerganov/llama.cpp")
    print("     llama-quantize.exe ... OR use 'ollama create' with FROM local dir:")
    print(f"     FROM {merged_dir}")
    print(f"  2) ollama create zahra-finetuned -f zahra_model/Modelfile.finetuned")
    return 0


if __name__ == "__main__":
    sys.exit(main())
